### ISSUE TITLE
Collection replicas table not getting cleaned up

### ISSUE THREAD

**Issue by dynamic-entropy** [dmwm/CMSRucio#471]
The following rse has 0 file replicas but still shows two empty dataset replicas. 

```
rucio list-datasets-rse T0_CH_CERN_Tape_Test --long
+---------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+
| DID                                                                                                     | LOCAL FILES/TOTAL FILES   | LOCAL BYTES/TOTAL BYTES   |
|---------------------------------------------------------------------------------------------------------+---------------------------+---------------------------|
| cms:/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM#3517e1b6-76e3-11e7-a0c8-02163e00d7b3 | 0/43                      | 0/108723314200            |
| cms:/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM#35197562-76e3-11e7-a0c8-02163e00d7b3 | 0/3                       | 0/4801598954              |
+---------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+
```

**Comment by dynamic-entropy** [comment]
What is the mode of operation for the table: 
1. Is it append only? Replicas are only marked unavailable but not deleted - in that case there is an issue with the API. 
2. If deleted replicas are indeed supposed to be cleaned up (rows removed) - `9201779`.

**Comment by dynamic-entropy** [comment]
@amanrique1

**Comment by dynamic-entropy** [comment]
Hi @yuyiguo 
This is the case with tables in both prod and int instances. Do you think the reasons could be similar to usage counter inconsistencies? https://github.com/dmwm/CMSRucio/issues/213

**Comment by yuyiguo** [comment]
I am not sure I understand your question. Please write the problem and how to reproduce it. @dynamic-entropy

**Comment by yuyiguo** [comment]
The datasets have no availability for this RSE/T0_CH_CERN_Tape_Test.  What is your point? Did you get inconsistent results? If so, can you show them?

**Comment by dynamic-entropy** [comment]
Yes, this issue stems from the assumption that 
> "unavailable" space in rucio - is data that is not at the RSE but expected to be.

Please, see https://github.com/dmwm/CMSRucio/issues/212#:~:text=Unavailable%3A%20data%20volume%20pending%20transfer%20to%20the%20site

So, lets check the rse-usage for `T0_CH_CERN_Tape_Test`:
```
➜  ~ rucio list-rse-usage T0_CH_CERN_Tape_Test
USAGE:
------
  rse_id: 14366bf923854ad39ebad6d6b19644c4
  source: expired
  used: 0.000 B
  updated_at: 2023-07-01 05:10:17
  rse: T0_CH_CERN_Tape_Test
------
  rse_id: 14366bf923854ad39ebad6d6b19644c4
  source: obsolete
  used: 0.000 B
  updated_at: 2023-07-01 05:11:00
  rse: T0_CH_CERN_Tape_Test
------
  rse_id: 14366bf923854ad39ebad6d6b19644c4
  source: rucio
  used: 0.000 B
  files: 0
  updated_at: 2023-04-13 22:28:08
  rse: T0_CH_CERN_Tape_Test
------
  rse_id: 14366bf923854ad39ebad6d6b19644c4
  source: unavailable  👈
  used: 113.525 GB 👈
  updated_at: 2022-09-12 18:00:01
  rse: T0_CH_CERN_Tape_Test
------
```

You will see that the unavailable space corresponds to the sum of the two replicas in the `CollectionReplicas` table, as shown by 
```
rucio list-datasets-rse T0_CH_CERN_Tape_Test --long
+---------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+
| DID                                                                                                     | LOCAL FILES/TOTAL FILES   | LOCAL BYTES/TOTAL BYTES   |
|---------------------------------------------------------------------------------------------------------+---------------------------+---------------------------|
| cms:/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM#3517e1b6-76e3-11e7-a0c8-02163e00d7b3 | 0/43                      | 0/108723314200            |
| cms:/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM#35197562-76e3-11e7-a0c8-02163e00d7b3 | 0/3                       | 0/4801598954              |
+---------------------------------------------------------------------------------------------------------+---------------------------+---------------------------+
```
or From the table
```
select * from cms_rucio_prod.collection_replicas where rse_id = (select id from cms_rucio_prod.rses where rse='T0_CH_CERN_Tape_Test');
```


However, there are no pending transfers to the `T0_CH_CERN_Tape_Test`.
1. There is no 'unavailable' replica in the `Replicas` table. 
```
select * from cms_rucio_prod.replicas where rse_id = (select id from cms_rucio_prod.rses where rse='T0_CH_CERN_Tape_Test');
```
2. There are no 'unavailable' (or any state) locks in the `Locks` table.
```
select * from cms_rucio_prod.locks where rse_id = (select id from cms_rucio_prod.rses where rse='T0_CH_CERN_Tape_Test');
```
3. There are no 'unavailable' locks in the `DatasetLocks` table.
```
select * from cms_rucio_prod.dataset_locks where rse_id = (select id from cms_rucio_prod.rses where rse='T0_CH_CERN_Tape_Test');
```

Let me know if you have more questions.
