### ISSUE TITLE
Rucio RSE usage and Account usage are not consistent 

### ISSUE THREAD

**Issue by Panos512** [dmwm/CMSRucio#593]
Dear @yuyiguo we have stumbled across the following issue and @dynamic-entropy suggested that it might be related to an issue you are working on.

We have identified some weird numbers when comparing account usage with RSE usage for one of our monitoring plots.
These numbers are from 30/8:

wma_prod usage in Cyfronet seems to be 246.651TB:

```
ppaparri@lxplus805 > rucio list-account-usage --rse T2_PL_Cyfronet 'wma_prod'
+----------------+------------+---------+--------------+
| RSE            | USAGE      | LIMIT   | QUOTA LEFT   |
|----------------+------------+---------+--------------|
| T2_PL_Cyfronet | 246.651 TB | 0.000 B | 0.000 B      |
+----------------+------------+---------+--------------+
```

The site's usage is reported as such:

```
ppaparri@lxplus805 > rucio list-rse-usage 'T2_PL_Cyfronet'
USAGE:
------
  rse_id: 4c47e3970a5145d8a94da3301c42d120
  source: expired
  used: 41.192 TB
  updated_at: 2023-08-30 09:30:28
  rse: T2_PL_Cyfronet
------
  rse_id: 4c47e3970a5145d8a94da3301c42d120
  source: obsolete
  used: 34.130 GB
  updated_at: 2023-08-30 09:30:19
  rse: T2_PL_Cyfronet
------
  rse_id: 4c47e3970a5145d8a94da3301c42d120
  source: rucio
  used: 275.802 TB
  files: 77411
  updated_at: 2023-08-30 09:29:27
  rse: T2_PL_Cyfronet
------
  rse_id: 4c47e3970a5145d8a94da3301c42d120
  source: static
  used: 400.000 TB
  updated_at: 2023-06-02 10:09:30
  rse: T2_PL_Cyfronet
------
  rse_id: 4c47e3970a5145d8a94da3301c42d120
  source: unavailable
  used: 1.338 TB
  updated_at: 2023-08-30 11:30:02
  rse: T2_PL_Cyfronet
------
```
The locked space is calculated as:
Rucio used - unavailable used - expired used
i.e.
275.80 TB - 1.338 TB - 41.192 TB

Which is 233.278TB.

This doesn't make sense, since it seems a single account is locking more data than all the locked data in the RSE.

We would appreciate some help on this one.

Thank you very much!
