### ISSUE TITLE
[BUG] Fix oidc sync script

### ISSUE THREAD

**Issue by dciangot** [dmwm/CMSRucio#684]
**Describe the bug**

Sync of IAM subjects is currently broken with pod failng with:

```
+ echo 'Syncing OIDC user identities'
+ ./syncaccount_oidc.py
Syncing OIDC user identities
Traceback (most recent call last):
  File "./syncaccount_oidc.py", line 101, in <module>
    token = response['access_token']
KeyError: 'access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./syncaccount_oidc.py", line 103, in <module>
    raise RuntimeError("ERROR oidc get token: {}".format(e))
RuntimeError: ERROR oidc get token: 'access_token'
```

**Possible Solution**

I'm going to test manually the refresh. A procedure worth putting into #648

**Related Issues**

A chilid issue of #428

**Comment by dciangot** [comment]
ok, looks like some update, had the config for IAM overwritten.. now is looking like this:
```
{
  "cms": {

    "issuer": "https://cms-auth.web.cern.ch/",

    "redirect_uris": [
      "CHANGEME e.g. https://cms-rucio-auth-int.cern.ch/auth/oidc_code",
      "CHANGEME e.g. https://cms-rucio-auth-int.cern.ch/auth/oidc_token"
    ],

    "client_id": "CLIENT_ID FOR USER AUTH",
    "registration_access_token": "",
    "client_secret": "CLIENT_SECRET FOR USER AUTH",

    "SCIM": {
     "client_id": "CLIENT_ID FOR SUBJ MAPPING",
      "registration_access_token": "",
      "client_secret": "CLIENT_SECRET FOR SUBJ MAPPING"
    }
  }
}
```

I'm going to recover the correct client IDs and propose a fix in flux. Same apply to: #685

**Comment by dciangot** [comment]
https://github.com/dmwm/rucio-flux/pull/235 should fix integration, @ericvaandering if you don't see any standing issue I'd go ahead and give it a try

**Comment by dynamic-entropy** [comment]
Hello Diego
Seems like https://github.com/dmwm/rucio-flux/pull/236 didn't help with the issue

**Comment by dciangot** [comment]
almost, now we need to check only that the secret match the correct client in IAM

**Comment by dciangot** [comment]
precisely, the client secret in the rucio-configs secrets does have a \n at the end, that broke the authN.

Steps I took to debug:
- created a sleep-infinity version of the cron job pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: rucio-cron-dciangot
  namespace: rucio
spec:
  containers:
  - command:
    - sleep
    - infinity 
    env:
    - name: RUCIO_HOME
      value: /opt/rucio-int
    - name: TEST_SUFFIX
      value: int
    - name: GITLAB_TOKEN
      valueFrom:
        secretKeyRef:
          key: gitlab_token
          name: rucio-secrets
    - name: MONIT_TOKEN
      valueFrom:
        secretKeyRef:
          key: monit_token
          name: rucio-secrets
    - name: IAM_SERVER
      value: https://cms-auth.web.cern.ch/
    - name: IAM_CLIENT_ID
      value: da4251a5-70c2-418d-a061-b861e779ed1e
    - name: IAM_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: oidc_iam_client_secret
          name: rucio-secrets
          optional: true
    image: registry.cern.ch/cmsrucio/rucio_client:latest
    imagePullPolicy: Always
    name: rucio-cron-12h
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/rucio/certs/
      name: usercert
    - mountPath: /opt/rucio/keys/
      name: userkey
    - mountPath: /cvmfs/grid.cern.ch
      name: grid-cern-ch
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cmsrucioint2-texirgwhj66f-node-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: usercert
    secret:
      defaultMode: 420
      secretName: daemons-fts-cert
  - name: userkey
    secret:
      defaultMode: 420
      secretName: daemons-fts-key
  - name: grid-cern-ch
    persistentVolumeClaim:
      claimName: csi-cvmfs-grid-pvc
```
- attached to it and played with code in `CMSRucio/docker/CMSRucioClient/scripts/syncaccount_oidc.py`
